services:

  registry:
    build: ./registry
    ports:
      - "8000:8000"

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_URL=http://registry:8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - registry
      - jaeger

  traffic:
    build: ./services/traffic
    environment:
      - REGISTRY_URL=http://registry:8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - registry
      - jaeger

  energy:
    build: ./services/energy
    environment:
      - REGISTRY_URL=http://registry:8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - registry
      - jaeger

  water:
    build: ./services/water
    environment:
      - REGISTRY_URL=http://registry:8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - registry
      - jaeger

  waste:
    build: ./services/waste
    environment:
      - REGISTRY_URL=http://registry:8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - registry
      - jaeger

  security:
    build: ./services/security
    environment:
      - REGISTRY_URL=http://registry:8000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - registry
      - jaeger

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.53
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
